### ISSUE TITLE
typo: subscribeToContiner

### ISSUE THREAD

**Issue by moltar** [molszanski/iti#20]
Should be `subscribeToContainer` I think.

Same for `subscribeToContinerSet`.

https://github.com/molszanski/iti/blob/4f7437e4f28629ba41321fad38d0adcc890ecebb/iti/src/library.new-root-container.ts#L131

**Comment by molszanski** [comment]
Right, thank you, will fix it <3

**Comment by molszanski** [comment]
Also need to clean up that file 🙈

**Comment by molszanski** [comment]
Hi @moltar. 
In the latest version [`0.5.0-next.0`](https://github.com/molszanski/iti/releases/tag/0.5.0-next.0) I've added support for disposing

**Comment by moltar** [comment]
@molszanski cool, will play around with it soon! thanks!

**Comment by molszanski** [comment]
@moltar 🔥
