### ISSUE TITLE
Event Hooks for dependencies

### ISSUE THREAD

**Issue by jacoobes** [molszanski/iti#39]
Class-based / object dependencies could implement event hooks.

For example

```ts
class Logger implements Init {
     init() {
       this.info("logger started");
     }
}
```
or 
```ts
{ init : () => this.info("logger started") }
```
There could be various hooks on dependencies that would be called when an iti even occurs. 
**Describe the solution you'd like**
**Naive solution**
For any / all events, loop through dependencies, calling corresponding function.
```ts
//init event occurs
for(dependency of Object.values(cache)) {
   dependency?.init?.()
}
```

**Comment by molszanski** [comment]
Not sure what you mean. 
There was a similar idea for disposing: 
https://github.com/molszanski/iti/issues/21
```ts
const container = createContainer()
  .add({
    stuff: () => {
       const s = new Stuff()
       s.init() // <- your idea is for this to happen automagically?
    }
  })

```

**Comment by molszanski** [comment]
Is this somehow related to this code?
https://github.com/sern-handler/handler/blob/main/src/handler/dependencies/provider.ts

**Comment by jacoobes** [comment]
Yes that code snippet is related. 

> Not sure what you mean. There was a similar idea for disposing: #21
> 
> Do you want something like this?
> 
> ```ts
> import {createContainer, Init} from 'iti'
> class Stuff implements Init {
>  init(){}
> } 
> 
> const container = createContainer()
>   .add({
>     stuff: () => {
>        const s = new Stuff()
>        s.init() // <- your idea is for this to happen automagically?
>     }
>   })
> ```

Yes, something similar to this. Was wondering if iti could automatically call init whenever a class / object has the init method.
the "init event" would be when the container is created.
I realize this might be specific to my own project, and may be out of the scope of iti

**Comment by molszanski** [comment]
This feels like this should be one of helper utils. 

What do you think?

```ts
// This code works, but just needs improved types
// const container = createContainer().add() 
container.on("containerUpserted", async (event) => {
  const item = await event.newContainer
  // @ts-ignore
  if (typeof item.init === "function") {
    // @ts-ignore
    item.init()
  }
})
```

https://stackblitz.com/edit/github-ocqyjw?file=src%2F_0.business-logic.ts,src%2F_1.wiring.ts,src%2FApp.tsx,src%2F_2.hooks.ts

<img width="1095" alt="CleanShot 2023-02-16 at 23 06 17@2x" src="https://user-images.githubusercontent.com/1117009/219497712-66e04f26-b75a-4220-93ad-a7ac53ce20af.png">

**Comment by jacoobes** [comment]
Hey, this looks great! Yeah! I would recommended adding interfaces for better typings, something like this:
```ts
interface Init {
  init() : void //or unknown
}
```
and a type predicate also
```ts
function isInitable(a: unknown): a is Init {
   return typeof a === 'object' && typeof a['init'] === 'function'
}
```
```ts
 const item = await event.newContainer
 if (isInitable(item)) {
   //should work without ts-ignore now
    item.init()
 }
```

For some reason, its not working on my computer. I assume the A dependency should

**Comment by molszanski** [comment]
Cool. Glad to help. I think this is a good idea to collect those tricks into an extras module and document them. And thanks for better types ;)

**Comment by jacoobes** [comment]
Hope all goes well!

**Comment by molszanski** [comment]
I think your approach is fine and should work without problems.

Almost all DI / container solutions have this lifecycle control of Transient / Singleton (stateful) approach
So this `init` calling would fail transient deps. But should work on `containerRequested` type of event 🤔

**Comment by jacoobes** [comment]
Makes sense. Thank you! I'll keep you posted. Thanks for a great module 😼
